macro (print_all_variables)
    message(STATUS "===================== VARIABLES BEGIN =====================")
    get_cmake_property(_variableNames VARIABLES)
    foreach (_variableName ${_variableNames})
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
    message(STATUS "===================== VARIABLES END =======================")
endmacro()
