Document: wxformbuilder
Title: Debian wxformbuilder Manual
Author: <insert document author here>
Abstract: This manual describes what wxformbuilder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wxformbuilder/wxformbuilder.sgml.gz

Format: postscript
Files: /usr/share/doc/wxformbuilder/wxformbuilder.ps.gz

Format: text
Files: /usr/share/doc/wxformbuilder/wxformbuilder.text.gz

Format: HTML
Index: /usr/share/doc/wxformbuilder/html/index.html
Files: /usr/share/doc/wxformbuilder/html/*.html
