#ifndef __wxFBDialogsFBSettings__
#define __wxFBDialogsFBSettings__

/**
@file
Subclass of FBSettings, which is generated by wxFormBuilder.
*/

#include "DialogGui.h"

//// end generated include

/** Implementing FBSettings */
class wxFBDialogsFBSettings : public FBSettings
{
	protected:
		// Handlers for FBSettings events.
		void m_idBoxOnCheckBox( wxCommandEvent& event );
		void m_handlerBoxOnCheckBox( wxCommandEvent& event );
		void m_sdbSizer1OnCancelButtonClick( wxCommandEvent& event );
		void m_sdbSizer1OnOKButtonClick( wxCommandEvent& event );
		
	public:
		/** Constructor */
		wxFBDialogsFBSettings( wxWindow* parent );
	//// end generated class members
};

#endif // __wxFBDialogsFBSettings__
