#!/bin/bash

set -e

# this function does the actual work of making the source package
# the version is passed to it as the first argument, below
function make_src_tarball
{
	# root source dir
	basedir=.

	# use a temporary directory
	tmpdir=wxformbuilder_$1.orig

	cp -R $basedir   ../$tmpdir
	cd ..
	
	#move debian dir to base
	mv  $tmpdir/install/linux/debian $tmpdir/debian
	
	tar czf $tmpdir.tar.gz $tmpdir
	rm -rf $tmpdir
}

changelog="output/Changelog.txt"

if [ ! -f $changelog ];
then
  echo "Sorry, could not find "$changelog". Need it to parse the version."
  exit 1
fi

cat "$changelog" |
while read line;
do
 version=`expr match "$line" '.*\([0-9]\.[0-9]\{1,2\}\.[0-9]\+\)'`
 if [ -n "$version" ]
 then
 echo "$version"
   # because I redirected cat to the while loop, bash spawned a subshell
   # this means "version" will go out of scop at the end of the loop
   # so I need to do everything here
   if [ ${#version} -ge 7 ]
   then
     version=${version/0/}
   fi
   make_src_tarball $version
   break
 fi
done

exit
