#ifndef __wxFBDialogsProjectSettings__
#define __wxFBDialogsProjectSettings__

/**
@file
Subclass of ProjectSettings, which is generated by wxFormBuilder.
*/

#include "DialogGui.h"

//// end generated include

/** Implementing ProjectSettings */
class wxFBDialogsProjectSettings : public ProjectSettings
{
	protected:
		// Handlers for ProjectSettings events.
		void m_sdbSizer2OnCancelButtonClick( wxCommandEvent& event );
		void m_sdbSizer2OnOKButtonClick( wxCommandEvent& event );
		
	public:
		/** Constructor */
		wxFBDialogsProjectSettings( wxWindow* parent );
	//// end generated class members
};

#endif // __wxFBDialogsProjectSettings__
