#ifndef __wxFBEventAdditionalPanel__
#define __wxFBEventAdditionalPanel__

/**
@file
Subclass of AdditionalPanel, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "event_GUI.h"

/** Implementing AdditionalPanel */
class wxFBEventAdditionalPanel : public AdditionalPanel
{
public:
	/** Constructor */
	wxFBEventAdditionalPanel( wxWindow* parent );
};

#endif // __wxFBEventAdditionalPanel__
