#ifndef __wxFBEventCommonPanel__
#define __wxFBEventCommonPanel__

/**
@file
Subclass of CommonPanel, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "event_GUI.h"

/** Implementing CommonPanel */
class wxFBEventCommonPanel : public CommonPanel
{
public:
	/** Constructor */
	wxFBEventCommonPanel( wxWindow* parent );
};

#endif // __wxFBEventCommonPanel__
